# Generated by Django 4.2.7 on 2023-11-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='taxi_class',
            field=models.CharField(choices=[('Эконом', 'ЭКОНОМ'), ('Комфорт', 'КОМФОРТ'), ('Комфорт+', 'КОМФОРТ+'), ('Бизнес', 'БИЗНЕС')], default='Эконом', max_length=8),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploeeys', to='backend.city')),
            ],
        ),
    ]
