# Generated by Django 4.2.7 on 2023-11-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_car_taxi_class_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='backend.city'),
        ),
    ]
