# Generated by Django 4.2.7 on 2023-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_employee_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/employees'),
        ),
    ]
