# Generated by Django 4.2.7 on 2023-11-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Газ', 'ГАЗ'), ('Бензин', 'БЕНЗИН'), ('Дизель', 'ДИЗЕЛЬ')], default='Газ', max_length=6),
        ),
    ]
