# Generated by Django 4.2.7 on 2023-11-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('АКПП', 'AT'), ('МКПП', 'MT')], default='АКПП', max_length=4),
        ),
    ]
